### ISSUE TITLE
Compiled andi.c with 'riscv64-unknown-elf-gcc -o andi andi.c' not passing test

### ISSUE THREAD

**Issue by TheRealBluesun** [nervosnetwork/ckb-vm#19]
Greetings all!

I'm trying to get the example programs that I compile myself to pass the tests, but it looks as though whatever I compile is not parsed correctly by the CKB VM.  The provided binaries pass just fine.  I've built the riscv toolchain as described [here](https://github.com/riscv/riscv-tools), and I've made no changes to the CKB-VM codebase.  It appears as though my compiled `andi` and the provided version have the same symbols, although different sizes.

Is there a compiler option I'm missing, or am I doing something silly I'm not seeing?

Thanks for any help you're able to provide.

**Comment by xxuejie** [comment]
@TheRealBluesun That indeed sounds like the correct step, can you try `riscv64-unknown-elf-objdump -d <your file name here> > dump.txt`, and post the dump file somewhere, so we can take a look?

**Comment by TheRealBluesun** [comment]
Thanks so much for the response!  

I've uploaded those two dumps, the compiled binary, and the output of cargo test here:  https://github.com/TheRealBluesun/vmdebuginfo

**Comment by xxuejie** [comment]
Hah I think I found the problem: in the test, we actually run `andi` using a 32-bit RISC-V machine: https://github.com/nervosnetwork/ckb-vm/blob/ac2b5cf858e30a4080beffa067a8fb9e8085d097/tests/test_misc.rs#L15. And when you compile `andi.c` using `riscv64-unknown-elf-gcc` you are getting a 64-bit RISC-V binary, that's why keeps breaking.

One more issue: have you made modifications to your andi.c? Cuz the assembly here: https://github.com/TheRealBluesun/vmdebuginfo/blob/master/objdump.txt#L7-L9 looks weird and shouldn't be the result of compiling `andi.c` file. For example, on my computer, compiling `andi.c` will result in a `main` section look like the following:

```
0000000000010192 <main>:
   10192:	1101                	addi	sp,sp,-32
   10194:	ec22                	sd	s0,24(sp)
   10196:	1000                	addi	s0,sp,32
   10198:	50100793          	li	a5,1281
   1019c:	fef42623          	sw	a5,-20(s0)
   101a0:	fec42783          	lw	a5,-20(s0)
   101a4:	9be1                	andi	a5,a5,-8
   101a6:	fef42423          	sw	a5,-24(s0)
   101aa:	fe842783          	lw	a5,-24(s0)
   101ae:	0007871b          	sext.w	a4,a5
   101b2:	50000793          	li	a5,1280
   101b6:	00f70463          	beq	a4,a5,101be <main+0x2c>
   101ba:	4785                	li	a5,1
   101bc:	a011                	j	101c0 <main+0x2e>
   101be:	4781                	li	a5,0
   101c0:	853e                	mv	a0,a5
   101c2:	6462                	ld	s0,24(sp)
   101c4:	6105                	addi	sp,sp,32
   101c6:	8082                	ret
```

Or if you are sure the correct `andi.c` file is used, you can use `riscv64-unknown-elf-gcc -O0 -o andi andi.c` to kill off optimizations done by gcc.

**Comment by TheRealBluesun** [comment]
> we actually run andi using a 32-bit RISC-V machine
Omg...how did I not see that.  Thank you!!  Changing it to `let result = run::<u64, SparseMemory>(&buffer, &vec![b"andi".to_vec()]);` makes the test pass.  I feel pretty silly now.

>the assembly here: [...] looks weird 

Looking back I believe that binary may have indeed been with `-O2` -- I was playing around with different assemblies; I'm pretty new to RISCV.

I do have some other questions, but this may not be the place for it -- I may drop in your telegram to talk shop :-).

Thank you all so much for your time and help!  Take care!
